---
project:
  title: PHPUnit Docker Container.
  author:
    name: Julien Breux
    email: julien.breux@gmail.com
image:
  base: composer/composer
versions:
- 5.0.8
- 5.0.7
- 5.0.6
- 5.0.5
- 5.0.4
- 5.0.3
- 5.0.2
- 5.0.1
- 5.0.0
- 4.8.16
- 4.8.5
- 4.8.4
- 4.8.3
- 4.7.7
- 4.6.10
- 4.6.6
